#!/bin/bash
#===========================================================================
# This script is installed in "/usr/local/bin"
#===========================================================================

if [ -f /home/<username>/.ssh/authorized_keys ] && \
   [ `cat /home/<username>/.ssh/authorized_keys | grep "^ssh-rsa" | wc -l` -ne 0 ] && \
   [ `cat /etc/ssh/sshd_config | grep "#PasswordAuthentication yes" | wc -l` -eq 1 ] ; then
  /usr/local/bin/disable_ssh_password_auth
  if [ "$1" != "container_init" ] ; then
    supervisorctl restart sshd
  fi
fi
