#!/bin/bash
# This script should be placed in /usr/local/bin

if [ -f /home/<username>/.ssh/authorized_keys ] && \
   [ `cat /home/<username>/.ssh/authorized_keys | grep "^ssh-rsa" | wc -l` -ne 0 ] && \
   [ `cat /etc/ssh/sshd_config | grep "#PasswordAuthentication yes" | wc -l` -eq 1 ]; then
  sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config
  sudo sh -c "echo \"<username>:\`date +%s | sha256sum | base64 | head -c 32 ; echo\`\" | chpasswd"
  chage -I -1 -m 0 -M 99999 -E -1 <username>
  if [ "$1" != "container_init" ]; then
    supervisorctl restart sshd
  fi
fi
