#!/bin/bash
# This script should be placed in /usr/local/bin

echo "Disabling ssh password auth..."
sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config
sudo sh -c "echo \"<username>:\`date +%s | sha256sum | base64 | head -c 32 ; echo\`\" | chpasswd"
chage -I -1 -m 0 -M 99999 -E -1 <username>
echo "Disabling ssh password auth done."