#!/bin/bash
#===========================================================================
# Init CA cert for log-* tools
#===========================================================================

export CREDHUB_SERVER="https://credhub.internal.paas:8844"
export CREDHUB_CLIENT="director_to_credhub"
BOSH_CERT_DIR="/data/shared/tools/certs"
BOSH_CA_CERT="${BOSH_CERT_DIR}/server-ca.crt"

#--- Colors and styles
export RED='\033[1;31m'
export YELLOW='\033[1;33m'
export GREEN='\033[1;32m'
export STD='\033[0m'
export BOLD='\033[1m'
export REVERSE='\033[7m'

#--- Create CA cert file
if [ ! -d ${BOSH_CERT_DIR} ] ; then
  mkdir -p ${BOSH_CERT_DIR}
fi

#--- Log to credhub
flag=`credhub f > /dev/null 2>&1`
if [ $? != 0 ] ; then
  flag=0
  while [ ${flag} = 0 ] ; do
    clear
    printf "%bEnter credhub \"${CREDHUB_CLIENT}\" password :%b " "${REVERSE}${YELLOW}" "${STD}" ; read CREDHUB_SECRET
    if [ "${CREDHUB_SECRET}" != "" ] ; then
      export CREDHUB_SECRET
      flag=1
    fi
  done

  credhub api > /dev/null 2>&1
  credhub login > /dev/null 2>&1
  if [ $? != 0 ] ; then
    printf "\n%bERROR : Bad credhub password for user \"${CREDHUB_CLIENT}\".%b\n\n" "${RED}" "${STD}"
    exit 1
  fi
fi

INTERNAL_CA=`credhub g -n /internalCA -j | jq .value.ca -r`
if [ $? = 0 ] ; then
  echo "${INTERNAL_CA}" > ${BOSH_CA_CERT}
  chmod 600 ${BOSH_CA_CERT}
  printf "\n\n"
else
  printf "\n\n%bERROR : \"/internalCA\" credhub value unknown.%b\n\n" "${RED}" "${STD}"
fi