#!/bin/bash
#===========================================================================
# Init CA cert for log-* tools
#===========================================================================

BOSH_CERT_DIR="/data/shared/tools/certs-test"
BOSH_CA_CERT="${BOSH_CERT_DIR}/server-ca.crt"

#--- Colors and styles
export RED='\033[1;31m'
export YELLOW='\033[1;33m'
export GREEN='\033[1;32m'
export STD='\033[0m'
export BOLD='\033[1m'
export REVERSE='\033[7m'

#--- Log to credhub
flag=`credhub f > /dev/null 2>&1`
if [ $? != 0 ] ; then
  printf "%bEnter CF LDAP user and password :%b\n" "${REVERSE}${YELLOW}" "${STD}"
  credhub api --server=https://credhub.internal.paas:8844 > /dev/null 2>&1
  credhub login
  if [ $? != 0 ] ; then
    printf "\n%bERROR : Bad LDAP authentication.%b\n\n" "${RED}" "${STD}"
    exit 1
  fi
fi

#--- Create CA cert file
if [ ! -d ${BOSH_CERT_DIR} ] ; then
  mkdir -p ${BOSH_CERT_DIR}
fi

INTERNAL_CA=`credhub g -n /internalCA -j | jq .value.ca -r`
if [ $? = 0 ] ; then
  echo "${INTERNAL_CA}" > ${BOSH_CA_CERT}
  chmod 600 ${BOSH_CA_CERT}
  printf "\n\n"
else
  printf "\n\n%bERROR : \"/internalCA\" credhub value unknown.%b\n\n" "${RED}" "${STD}"
fi