#!/bin/bash
#===========================================================================
# Log with mc (minio) cli
#===========================================================================

#--- Colors and styles
export RED='\033[1;31m'
export YELLOW='\033[1;33m'
export GREEN='\033[1;32m'
export STD='\033[0m'
export BOLD='\033[1m'
export REVERSE='\033[7m'

flagError=0

getCredhub() {
  #--- Test if parameter exist with non empty value, else get it from credhub
  if [ "${!1}" = "" ] ; then
    credhubGet=`credhub g -n $2 2>&1`
    result=`echo "${credhubGet}" | grep "Credential not found"`
    if [ "${result}" = "" ] ; then
      credhubValue=`echo "${credhubGet}" | grep "value: " | awk '{print $2}'`
      eval $1=`echo "${credhubGet}" | grep "value: " | awk '{print $2}'`
    else
      printf "\n\n%bERROR : \"$2\" credhub value unknown.%b\n\n" "${RED}" "${STD}"
      flagError=1
    fi
  fi
}

#--- Log to credhub
status=`env | grep CREDHUB_SECRET`
if [ "${status}" = "" ] ; then
  if [ ! -s "${BOSH_CA_CERT}" ] ; then
    printf "\n%bERROR : CA cert file \"${BOSH_CA_CERT}\" unknown.%b\n\n" "${RED}" "${STD}"
    flagError=1
  else
    export CREDHUB_SERVER="https://credhub.internal.paas:8844"
    export CREDHUB_CLIENT="director_to_credhub"
    export CREDHUB_CA_CERT="${BOSH_CA_CERT}"
    flag=0
    while [ ${flag} = 0 ] ; do
      clear
      printf "%bEnter credhub password :%b " "${REVERSE}${YELLOW}" "${STD}" ; read -s CREDHUB_SECRET
      if [ "${CREDHUB_SECRET}" != "" ] ; then
        flag=1
      fi
    done

    export CREDHUB_SECRET
    credhub api > /dev/null 2>&1
    credhub login > /dev/null 2>&1
    if [ $? = 1 ] ; then
      printf "\n%bERROR : Bad credhub password.\nConnexion failed.%b\n\n" "${RED}" "${STD}"
      flagError=1
    fi
  fi
fi

#--- Log to minio
if [ "${flagError}" = "0" ] ; then
  getCredhub "S3_SECRET_KEY" "/micro-bosh/minio-private-s3/s3_secretkey"
  if [ ${flagError} = 0 ] ; then
    mc config host add minio http://private-s3.internal.paas:9000 private-s3 ${S3_SECRET_KEY} > /dev/null 2>&1
    if [ $? = 1 ] ; then
      printf "\n%bERROR : Connexion failed.%b\n\n" "${RED}" "${STD}"
    else
      mc ls minio
      printf "\n"
    fi
  fi
fi