#!/bin/bash
#===========================================================================
# Log with fly (concourse) cli
#===========================================================================

#--- Colors and styles
export RED='\033[1;31m'
export YELLOW='\033[1;33m'
export GREEN='\033[1;32m'
export STD='\033[0m'
export BOLD='\033[1m'
export REVERSE='\033[7m'

flagError=0

getCredhub() {
  #--- Test if parameter exist with non empty value, else get it from credhub
  if [ "${!1}" = "" ] ; then
    credhubGet=`credhub g -n $2 2>&1`
    result=`echo "${credhubGet}" | grep "Credential not found"`
    if [ "${result}" = "" ] ; then
      credhubValue=`echo "${credhubGet}" | grep "value: " | awk '{print $2}'`
      eval $1=`echo "${credhubGet}" | grep "value: " | awk '{print $2}'`
    else
      printf "\n\n%bERROR : \"$2\" credhub value unknown.%b\n\n" "${RED}" "${STD}"
      flagError=1
    fi
  fi
}

#--- Log to credhub
flagError=0
flag=`credhub f > /dev/null 2>&1`
if [ $? != 0 ] ; then
  printf "%bEnter CF LDAP user and password :%b\n" "${REVERSE}${YELLOW}" "${STD}"
  credhub api --server=https://credhub.internal.paas:8844 > /dev/null 2>&1
  credhub login
  if [ $? != 0 ] ; then
    printf "\n%bERROR : Bad LDAP authentication.\nConnexion failed.%b\n\n" "${RED}" "${STD}"
    flagError=1
  fi
fi

#--- Log to fly
if [ ${flagError} = 0 ] ; then
  getCredhub "OPS_DOMAIN" "/secrets/cloudfoundry_ops_domain"
  if [ ${flagError} = 0 ] ; then
    if [ "${FLY_PASSWORD}" = "" ] ; then
      flag=0
      while [ ${flag} = 0 ] ; do
        clear
        printf "%bEnter concourse \"atc\" Password :%b " "${REVERSE}${YELLOW}" "${STD}" ; read -s FLY_PASSWORD
        if [ "${FLY_PASSWORD}" != "" ] ; then
          flag=1
        fi
      done
    fi
    fly login -c https://elpaaso-concourse-micro.${OPS_DOMAIN} -k -u atc -p ${FLY_PASSWORD}
    if [ $? = 1 ] ; then
      FLY_PASSWORD=""
      printf "\n\n%bERROR : Connexion failed.%b\n\n" "${RED}" "${STD}"
    else
      fly builds
      printf "\n"
    fi
  fi
fi