#!/bin/bash
#===========================================================================
# Log with CF cli
#===========================================================================

#--- Colors and styles
export RED='\033[1;31m'
export YELLOW='\033[1;33m'
export GREEN='\033[1;32m'
export STD='\033[0m'
export BOLD='\033[1m'
export REVERSE='\033[7m'

getCredhub() {
  #--- Test if parameter exist with non empty value, else get it from credhub
  if [ "${!1}" = "" ] ; then
    credhubGet=`credhub g -n $2 2>&1`
    result=`echo "${credhubGet}" | grep "Credential not found"`
    if [ "${result}" = "" ] ; then
      credhubValue=`echo "${credhubGet}" | grep "value: " | awk '{print $2}'`
      eval $1=`echo "${credhubGet}" | grep "value: " | awk '{print $2}'`
    else
      printf "\n\n%bERROR : \"$2\" credhub value unknown.%b\n\n" "${RED}" "${STD}"
      flagError=1
    fi
  fi
}

#--- Log to credhub
export CREDHUB_SERVER="https://credhub.internal.paas:8844"
export CREDHUB_CA_CERT="${BOSH_CA_CERT}"
flagError=0

if [ ! -s "${BOSH_CA_CERT}" ] ; then
  printf "\n%bERROR : CA cert file \"${BOSH_CA_CERT}\" unknown.%b\n\n" "${RED}" "${STD}"
  flagError=1
else
  flag=`credhub f 2>&1 | grep "not currently authenticated"`
  if [ "${flag}" != "" ] ; then
    printf "%bEnter CF LDAP user and password :%b\n" "${REVERSE}${YELLOW}" "${STD}"
    credhub login
    if [ $? != 0 ] ; then
      printf "\n%bERROR : Bad LDAP authentication.\nConnexion failed.%b\n\n" "${RED}" "${STD}"
      flagError=1
    fi
  fi
fi

#--- Log to CF
if [ "${flagError}" = "0" ] ; then
  flag=0
  while [ ${flag} = 0 ] ; do
    clear
    printf "%bEnter CF User :%b " "${REVERSE}${YELLOW}" "${STD}" ; read CF_USER
    if [ "${CF_USER}" != "" ] ; then
      flag=1
    fi
  done

  getCredhub "SYSTEM_DOMAIN" "/secrets/cloudfoundry_system_domain"
  if [ ${flagError} = 0 ] ; then
    cf login -a https://api.${SYSTEM_DOMAIN} -u ${CF_USER}
    if [ $? = 1 ] ; then
      printf "\n%bERROR : Connexion failed.%b\n\n" "${RED}" "${STD}"
    else
      printf "\n\n"
    fi
  fi
fi