#!/bin/bash
# This script should be placed in /usr/local/bin
# Used at container startup

if [ -z "$SSH_PUBLIC_KEY" ] && [ ! -f /home/<username>/.ssh/authorized_keys ]
then
  mkdir -p /home/<username>/.ssh
  chmod 700 /home/<username>/.ssh
  echo "$SSH_PUBLIC_KEY" > /home/<username>/.ssh/authorized_keys
  chmod 600 /home/<username>/.ssh/authorized_keys
  /usr/local/bin/disable_ssh_password_auth
fi

/usr/local/bin/check_ssh_security container_init
/usr/bin/supervisord -c /etc/supervisor/supervisord.conf