#!/bin/bash
#===========================================================================
# Switch to Bosh deployment within bosh director
#===========================================================================

#--- Colors and styles
export RED='\033[1;31m'
export YELLOW='\033[1;33m'
export GREEN='\033[1;32m'
export STD='\033[0m'
export BOLD='\033[1m'
export REVERSE='\033[7m'

result=$(bosh env | grep "not logged in" 2>&1)
if [ "${result}" != "" ] ; then
  printf "\n\n%bERROR : You are not connected to bosh director.%b\n\n" "${RED}" "${STD}"
else
  #--- Select specific deployment (BOSH_DEPLOYMENT variable)
  deployments=$(bosh deployments --column=Name | grep -vE "^Name$|^Succeeded$|^[0-9]* deployments$")
  if [ "$1" != "" ] ; then
    flag=$(echo "${deployments}" | grep "$1")
    if [ "${flag}" = "" ] ; then
      unset BOSH_DEPLOYMENT
    else
      export BOSH_DEPLOYMENT="$1"
      bosh instances
    fi
  else
    printf "\n%bSelect a specific deployment in the list:%b\n%s" "${REVERSE}${YELLOW}" "${STD}" "${deployments}"
    printf "\n\n%bYour choice :%b " "${GREEN}${BOLD}" "${STD}" ; read choice
    if [ "${choice}" = "" ] ; then
      unset BOSH_DEPLOYMENT
    else
      flag=$(echo "${deployments}" | grep "${choice}")
      if [ "${flag}" = "" ] ; then
        unset BOSH_DEPLOYMENT
      else
        export BOSH_DEPLOYMENT="${choice}"
        bosh instances
      fi
    fi
  fi
  printf "\n"
fi